# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 769004f87ccd9c08ef25cb4d5f895ff7704cca6c81aae16bee1afae02310acaea69657fb48af0975cd1d7dc7a823560031db17cf6c0e9037337f58dc47b08ab8

test:
  secret_key_base: dbc4f93504da968bab128e120a8e2103fb8d07a4f324deeea9c0dea7977433d1ca2f6bffd5f82226a47542ec39ee14c2441894b51b403a5d22739c9665fb373a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
